export const ACTIONS = {
    NEW_GAME: 'NEW_GAME',
    END_GAME: 'END_GAME',
    CREATE_TICKET: 'CREATE_TICKET',
    NEW_CALL: 'NEW_CALL',
    RESET: 'RESET',
    DECREMENT_STAKE: 'DECREMENT_STAKE',
    INCREMENT_STAKE: 'INCREMENT_STAKE'
};
